
version: "3"
volumes:
  db-store:

services:

  mysql:
    image: mysql:8.0
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: todoApp
      TZ: 'Asia/Tokyo'
    ports:
      - 4306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/init:/docker-entrypoint-initdb.d
