
version: "3"
volumes:
  db-store:

services:

  postgresql:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: nest_db
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/
